; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html
[platformio]
default_envs = T_Embed_CC1101

[env:T_Embed_CC1101]
platform = espressif32@6.5.0
board = T_Embed_PN532
framework = arduino
lib_extra_dirs = lib_T_Embed_CC1101

upload_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps = 
    mathertel/RotaryEncoder@^1.5.3
    lewisxhe/XPowersLib

build_flags = 
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DCORE_DEBUG_LEVEL=3
    -DDISABLE_ALL_LIBRARY_WARNINGS
    -I src/Device_T_Embed_CC1101
    -I src/Device_T_Embed_CC1101/Screens
    -I src/Device_T_Embed_CC1101/Policies
    -I src/Device_All
    -I src/Device_All/Screens

lib_ldf_mode = deep+
build_src_filter = +<*> -<Device_*/**/*> +<Device_T_Embed_CC1101/**/*> +<Device_All/**/*>

[env:unit_tests]
platform = native
test_framework = unity
build_flags = 
    -std=c++11
    -I src/Device_Mock
    -I src/Device_Native/Screens
    -I src/Device_Mock/Policies
    -I src/Device_All
    -I src/Device_All/Screens
test_build_src = yes
build_src_filter = +<*> -<Device_*/**/*> +<Device_Mock/**/*> +<Device_All/**/*> -<**/main.cpp>

[env:run_simulator]
platform = native
build_flags = 
    -std=c++11
    -I src/Device_Native
    -I src/Device_Native/Screens
    -I src/Device_Native/Policies
    -I src/Device_All
    -I src/Device_All/Screens
    -lSDL2
    -lSDL2_ttf
extra_scripts = pre:sdl2_build.py
build_src_filter = +<*> -<Device_*/**/*> +<Device_Native/**/*> +<Device_All/**/*>
targets = exec